# KNN
## 선호도 data 활용

In [15]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix

In [3]:
# 데이터 불러오기
like = pd.read_csv('e:/Git_private_dodo_Riley/laptop_desktop/Code_SJH/통계학머신러닝_양진욱/data/like.csv')
like.columns = ['talk','book','travel','school','tall','skin','muscle','like_level']
like.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   talk        14 non-null     int64 
 1   book        14 non-null     int64 
 2   travel      14 non-null     int64 
 3   school      14 non-null     int64 
 4   tall        14 non-null     int64 
 5   skin        14 non-null     int64 
 6   muscle      14 non-null     int64 
 7   like_level  14 non-null     object
dtypes: int64(7), object(1)
memory usage: 1.0+ KB


In [7]:
# feature와 label 지정
X = np.array(like.drop('like_level', axis=1))
y = np.array(like.like_level)

X.shape,y.shape

((14, 7), (14,))

In [9]:
# 정규화
scaler = StandardScaler()
X = scaler.fit(X).transform(X)
X

array([[-1.26962211,  1.34164079, -0.8461218 , -0.98782916,  2.06644812,
         1.29927838, -0.59160798],
       [ 0.21160368, -0.36590203,  0.57536283, -0.3592106 ,  0.04805693,
        -0.09994449,  1.77482393],
       [-0.28213825, -0.93508297,  1.04919104,  0.26940795, -0.62474013,
         0.36646313,  1.18321596],
       [ 1.69282948, -0.36590203,  0.10153462, -1.61644772, -1.29753719,
        -1.96557498, -1.77482393],
       [-0.28213825,  0.77245985, -1.31995001,  0.89802651,  0.720854  ,
         0.83287076,  0.        ],
       [ 0.70534562, -1.50426391,  0.10153462, -0.98782916, -1.29753719,
        -1.03275974, -1.77482393],
       [-0.77588018,  1.91082173,  0.10153462,  0.26940795,  0.04805693,
         0.83287076,  0.        ],
       [-1.26962211,  0.20327891,  1.52301925,  0.26940795, -1.29753719,
         0.36646313,  0.59160798],
       [ 1.19908755, -0.93508297, -1.79377823,  1.52664507,  0.04805693,
        -1.03275974, -0.59160798],
       [-0.28213825,  0.7724

In [11]:
# 모델 학습
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X,y)

KNeighborsClassifier()

In [13]:
# 원래 데이터를 넣어서 예측
y_pred = knn.predict(X)
y_pred

array(['1타입', '2타입', '2타입', '3타입', '1타입', '3타입', '1타입', '2타입', '3타입',
       '1타입', '3타입', '1타입', '2타입', '3타입'], dtype=object)

In [14]:
y

array(['1타입', '2타입', '2타입', '3타입', '1타입', '3타입', '1타입', '2타입', '3타입',
       '1타입', '3타입', '1타입', '2타입', '3타입'], dtype=object)

In [16]:
# 모델 평가
print(f' confusion matrix : \n {confusion_matrix(y,y_pred)} \n')
print(f' classification report : \n {classification_report(y,y_pred)} \n')

 confusion matrix : 
 [[5 0 0]
 [0 4 0]
 [0 0 5]] 

 classification report : 
               precision    recall  f1-score   support

         1타입       1.00      1.00      1.00         5
         2타입       1.00      1.00      1.00         4
         3타입       1.00      1.00      1.00         5

    accuracy                           1.00        14
   macro avg       1.00      1.00      1.00        14
weighted avg       1.00      1.00      1.00        14
 



## 상품구매여부 데이터 활용

In [109]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier, KNeighborsRegressor
from sklearn.metrics import classification_report, confusion_matrix

In [153]:
# 데이터 불러오기
buy = pd.read_csv('e:/Git_private_dodo_Riley/laptop_desktop/Code_SJH/통계학머신러닝_양진욱/data/buy.csv')
buy.columns = ['age','income','purchase']
buy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   age       20 non-null     int64 
 1   income    20 non-null     int64 
 2   purchase  20 non-null     object
dtypes: int64(2), object(1)
memory usage: 608.0+ bytes


In [111]:
buy.head()

age  income purchase
0   26     160       구매
1   35     210      비구매
2   26     220     비구매 
3   29     260       구매
4   22     110      비구매

In [133]:
buy.purchase.value_counts()

비구매    12
구매      8
Name: purchase, dtype: int64

# KNN classification

In [136]:
# 피쳐 및 라벨 지정
X = buy.iloc[:,[0,1]]
y = buy.iloc[:,2]

In [137]:
# 피쳐 value 정규화
scaler = StandardScaler()
X = scaler.fit(X).transform(X)

In [138]:
# 분류모델 학습 및 예측
classifier = KNeighborsClassifier(n_neighbors = 2)
classifier.fit(X, y)

KNeighborsClassifier(n_neighbors=2)

In [139]:
# 실제 피쳐값으로 예측 라벨값 생성 
y_pred = classifier.predict(X)
y_pred 

array(['구매', '비구매', '비구매', '구매', '비구매', '비구매', '구매', '비구매', '비구매', '구매',
       '구매', '비구매', '구매', '구매', '구매', '구매', '비구매', '비구매', '구매', '구매'],
      dtype=object)

In [140]:
# 실제 라벨값과 예측 라벨값을 이용해 평가 지표 계산
print(confusion_matrix(y, y_pred)) 
print(classification_report(y, y_pred))

[[8 0]
 [3 9]]
              precision    recall  f1-score   support

          구매       0.73      1.00      0.84         8
         비구매       1.00      0.75      0.86        12

    accuracy                           0.85        20
   macro avg       0.86      0.88      0.85        20
weighted avg       0.89      0.85      0.85        20



# KNN regression

In [154]:
# 정수 인코딩
buy_int = np.array([0]*len(buy))
buy_int[buy.purchase=='구매']=1
buy_int[buy.purchase=='비구매']=0
buy.purchase = buy_int
buy.head()

age  income  purchase
0   26     160         1
1   35     210         0
2   26     220         0
3   29     260         1
4   22     110         0

In [144]:
buy_origin = buy
buy_origin.head()

age  income  purchase
0   26     160         1
1   35     210         0
2   26     220         0
3   29     260         1
4   22     110         0

In [166]:
# 정규화
scaler = StandardScaler()
buy = scaler.fit(buy).transform(buy)
buy = pd.DataFrame(buy)
buy.columns = ['age','income','purchase']
buy.head()

age    income  purchase
0 -0.677439 -0.813024  1.224745
1  1.016158 -0.259946 -0.816497
2 -0.677439 -0.149331 -0.816497
3 -0.112906  0.293131  1.224745
4 -1.430149 -1.366101 -0.816497

In [167]:
# 피쳐 및 라벨 지정(피쳐=수입,구매여부 라벨=나이)
# 즉 수입과 구매여부에 따라 나이를 알아보겠다는 뜻
X = buy.iloc[:, [1,2]].values
y = buy.iloc[:, [0]].values

# train/test 데이터 분리
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((16, 2), (4, 2), (16, 1), (4, 1))

In [168]:
# 모델 학습
model = KNeighborsRegressor() # 수치 예측
model.fit(X_train, y_train)

# 예측값 계산
y_pred = model.predict(X_test)

In [169]:
# r2 score 계산
model.score(X_test,y_test)

-0.4933333333333336

In [170]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)
# 애초에 데이터 자체가 모형에 맞지않으니...결과가 엉망
# r2 score가 음수라는건 단순히 평균값으로 예측한거보다 결과가 안좋다는 뜻

-0.4933333333333336